var DATA = {
  personal_info: {
    name: "Pedro Viana Maya de Oliveira Pires",
    intro:
      "Backend Python developer with knowledge in Project Management, Team Leading, Frontend and DevOps",
    location: "Portugal, Azores",
    id: "pedromayapires",
    email: "@gmail.com",
    linkedin: "www.linkedin.com/in/",
    github: ".github.io",
  },
  degrees: [
    {
      name: "Computer engineering",
      // period: [ '2004-09-15', '2010-09-15' ],
      location: "F.C.T. Universidade Nova de Lisboa",
    },
    // {
    //   name: 'Mathematics',
    //   period: [ '2003-09-15', '2004-07-15' ],
    //   location:
    //     'Faculdade de Ciências e Tecnologia da Universidade Nova de Lisboa'
    // }
  ],
  languages: [
    {
      language: "Portuguese",
      level: "Native",
    },
    {
      language: "English",
      level: "Fluent",
    },
    // {
    //   language: "Spanish",
    //   level: "Basic level",
    // },
  ],
  // tech_to_highlight: new Set(
  tech_to_highlight: {
    Python: true,
    MySql: true,
    PostgreSql: true,
    Django: true,
    PyTest: true,
    Docker: true,
    FastAPI: true,
    AWS: true,
    Flask: true,
    Ansible: true,
    Airflow: true,
    Panda: true,
    Numpy: true,
    "GitHub Actions": true,
    "GitHub Workflows": true,
    MongoDB: true,
    ElasticSearch: true,
    Redis: true,
    Azure: true,
    "Google functions": true,
    "Co-Pilot": true,
  },
  // ]),
  // extra_tech_to_add: {
  //   // tech: number of months
  //   Pandas: 1,
  // },
  clients: [
    {
      name: "Abelhas Intemporais",
      projects: [
        {
          name: "ScalaBit",
          team_size: 6,
          period: ["2025-05-12", "2025-09-02"],
          roles: ["Backend", "DevOps"],
          goals: [
            "Created and improved Git actions and workflows to improve reliability of other repositories code and integrity",
            "Created microservices",
            "Added unit tests for code integrity.",
            "Conducted code reviews",
          ],
          tech: [
            "Agile",
            "Python",
            "Git",
            "GitHub Actions",
            "GitHub Workflows",
            "Rest",
            "FastAPI",
            "PyTest",
            "Docker",
          ],
        },
        {
          name: "KCS-IT",
          team_size: 4,
          period: ["2024-09-16", "2025-02-02"],
          roles: ["Backend", "Database Architect"],
          goals: [
            "Created microservices and their respective databases",
            "Added unit tests and Postman scripts for code integrity.",
          ],
          tech: [
            "Agile",
            "Python",
            "Ubuntu",
            "Git",
            "Rest",
            "FastAPI",
            "Postman",
            "PyTest",
            "Docker",
          ],
        },
      ],
    },
    {
      name: "Ausy",
      projects: [
        {
          name: "A.I.",
          team_size: 1,
          period: ["2024-04-02", "2024-07-15"],
          roles: ["Backend"],
          goals: [
            "Created a microservice using the help of Co-Pilot as a usefulness and efficiency test of A.I.",
          ],
          tech: [
            "Agile",
            "Python",
            "Ubuntu",
            "Git",
            "Virtualbox",
            "Co-Pilot",
            "PyTest",
            "Rest",
          ],
        },
        {
          name: "Microservices",
          team_size: 3,
          period: ["2022-07-18", "2024-04-02"],
          roles: ["Backend"],
          goals: [
            "Created and improved microservices to connect multiple consultancy APIs ",
            "Added unit tests and Postman scripts for code integrity.",
          ],
          tech: [
            "Agile",
            "Python",
            "Ubuntu",
            "Git",
            "Virtualbox",
            "Rest",
            "Dapr",
            "Docker",
            "FastAPI",
            "Postman",
            "PyTest",
            "MySql",
          ],
        },
      ],
    },
    {
      name: "Dohop",
      projects: [
        {
          name: "Travelling search engine",
          team_size: 3,
          period: ["2021-02-02", "2021-09-02"],
          roles: ["Backend"],
          goals: [
            "Created and improved webservices to import and transform data from different clients",
            "Added unit tests and Postman scripts for code integrity.",
          ],
          tech: [
            "Agile",
            "Python",
            "Ubuntu",
            "Git",
            "PyTest",
            "Postman",
            "Virtualbox",
            "Rest",
          ],
        },
      ],
    },
    {
      name: "Affinity",
      projects: [
        {
          name: "Travelling search engine",
          team_size: 4,
          period: ["2019-10-02", "2020-05-02"],
          roles: ["Backend", "Database Architect", "Team leader"],
          goals: [
            "Managed a team",
            "Created the backend and database structure for a customer support tool",
            "Conducted code reviews",
          ],
          tech: [
            "Agile",
            "Python",
            "Django",
            "Docker",
            "Ubuntu",
            "Git",
            "PostgreSql",
            "Virtualbox",
            "MySql",
            "React",
            "Rest",
          ],
        },
        {
          name: "Food supplements",
          team_size: 3,
          period: ["2019-07-02", "2019-10-02"],
          roles: ["Backend", "Frontend"],
          goals: [
            "Created and improved Google cloud functions",
            "Created a frontend for users and to allow better local data management",
          ],
          tech: [
            "Agile",
            "Python",
            "Google functions",
            "Ubuntu",
            "AngularJs",
            "Javascript",
            "Virtualbox",
            "Rest",
          ],
        },
        {
          name: "Security software",
          team_size: 2,
          period: ["2019-04-02", "2019-07-02"],
          roles: ["Backend", "Frontend"],
          goals: [
            "Created the backend code and the database and added webhooks for a security scan report from a tool",
            "Created frontend code but not the design",
          ],
          tech: [
            "Agile",
            "Python",
            "Django",
            "Ubuntu",
            "React",
            "Git",
            "PostgreSql",
            "Virtualbox",
            "Docker",
            "Rest",
            "Webhooks",
          ],
        },
        {
          name: "Sourcing services",
          team_size: 1,
          period: ["2018-10-02", "2019-04-02"],
          roles: ["Backend", "Project manager", "Database Architect"],
          goals: [
            "Added and optimized code",
            "Improved database structure and Django's fixtures and migrations",
            "Advised for roles to have and interviewed candidates",
            "Created web scraping scripts",
          ],
          tech: [
            "Agile",
            "Python",
            "Django",
            "Ubuntu",
            "Git",
            "AWS",
            "Virtualbox",
            "PostgreSql",
            "Scrapy",
            "Beautiful Soup",
            "AWS",
            "Rest",
          ],
        },
        {
          name: "Product assortment for retailers",
          team_size: 7,
          period: ["2018-04-02", "2018-10-02"],
          roles: ["Backend", "DevOps"],
          goals: [
            "Improved server performance through configuration",
            "Optimized code and database procedures",
            "Server software installation",
            "Added and and improved existing features",
            "Applied math equations in Python using Panda and Numpy",
          ],
          tech: [
            "Agile",
            "Ansible",
            "Airflow",
            "Python",
            "Flask",
            "CentOS",
            "Git lab",
            "SupervisorD",
            "Virtualbox",
            "Panda",
            "Numpy",
            "Ubuntu",
            "AWS",
            "Rest",
          ],
        },
      ],
    },
    {
      name: "Babel",
      projects: [
        {
          name: "Data collector",
          team_size: 3,
          period: ["2017-12-26", "2018-04-02"],
          roles: [
            "Backend",
            "Project manager",
            "Team leader",
            "Database Architect",
          ],
          goals: [
            "Got the requirements to create a data collector based on tool called uData",
            "Managed the project and a small team",
            "Created a Rest data collector to import and display data from different government entities",
            "Added national id authentication and verification to the tool",
          ],
          tech: [
            "Agile",
            "Python",
            "MongoDB",
            "Flask",
            "ElasticSearch",
            "Redis",
            "CentOS",
            "Git",
            "Ubuntu",
            "Virtualbox",
            "Azure",
            "Rest",
            "ID software",
          ],
        },
      ],
    },
    {
      name: "Agap2It",
      projects: [
        {
          name: "Script maintenance and application testing",
          team_size: 1,
          period: ["2017-09-11", "2017-11-02"],
          roles: ["Backend", "Database Architect"],
          goals: [
            "Development and maintenance of Python scripts, database structural optimization",
            "Network bandwidth testing using different software tools",
          ],
          tech: ["Python", "MySql", "NodeJs", "PHP", "Rest"],
        },
      ],
    },
    {
      name: "Leads4Sales",
      projects: [
        {
          name: "Marketing & Call center",
          team_size: 6,
          period: ["2016-06-02", "2017-09-02"],
          roles: ["Backend", "Frontend", "Database Architect"],
          goals: [
            "Developed, updated and maintained backoffice pages",
            "Created and maintained existing landing pages",
            "Database maintenance and improvement, minor helpdesk and system administration tasks",
          ],
          tech: [
            "NodeJs",
            "AngularJs",
            "PostgreSql",
            "Express",
            "Html",
            "CSS",
            "Mercurial",
            "Javascript",
            "PHP",
            "Virtualbox",
            "Ubuntu",
            "Rest",
          ],
        },
      ],
    },
    {
      name: "Instituto de Medicina Molecular",
      projects: [
        {
          name: "H.R. Manager",
          team_size: 1,
          period: ["2016-03-02", "2016-06-02"],
          roles: [
            "Backend",
            "Frontend",
            "Project manager",
            "Database Architect",
          ],
          goals: [
            "Got the requirements from the Human Resources team for a tool",
            "Created a tool to import and match information from H.R., from several files and existing database, to place in a new database structure",
          ],
          tech: [
            "Python",
            "Django",
            "Javascript",
            "Jquery",
            "Html",
            "Sql Server",
            "CSS",
            "Git",
            "Ldap",
            "Virtualbox",
            "Ubuntu",
            "Rest",
          ],
        },
        {
          name: "Resource, user and document manager",
          team_size: 1,
          period: ["2015-09-02", "2016-03-02"],
          roles: [
            "Backend",
            "Frontend",
            "Project manager",
            "Database Architect",
          ],
          goals: [
            "Got the requirements from different research departments for a scientific equipment booking system with user assistance",
            "Created the backend, frontend and database for that web application with LDAP user authentication from the existing infrastructure",
            "Created and added a simple document/file manager to that tool, as an application in Django, to the mentioned booking system",
          ],
          tech: [
            "Python",
            "Django",
            "Javascript",
            "Jquery",
            "Html",
            "Sql Server",
            "CSS",
            "Git",
            "Ldap",
            "Virtualbox",
            "Ubuntu",
            "Rest",
          ],
        },
      ],
    },
    {
      name: "Instituto Gulbenkian de ciência",
      projects: [
        {
          name: "Document manager",
          team_size: 1,
          period: ["2013-01-02", "2015-07-02"],
          roles: [
            "Backend",
            "Frontend",
            "Project manager",
            "Database Architect",
          ],
          goals: [
            "Got the requirements from the administration team for a document manager tool",
            "Created the full database to support the information for that tool",
            "Created the backend and frontend code for the tool",
            "Allowed the communication and authentication between the tool and the existing infrastructure of the institute",
          ],
          tech: [
            "Python",
            "Django",
            "Javascript",
            "Jquery",
            "Html",
            "Ldap",
            "MySql",
            "Soap",
            "Rest",
            "CSS",
            "Git",
            "Virtualbox",
            "Ubuntu",
          ],
        },
        {
          name: "Resource manager",
          team_size: 4,
          period: ["2010-12-02", "2013-01-02"],
          roles: ["Backend", "Frontend", "Database Architect"],
          goals: [
            "Added and improved features and security to a software tool that allowed authenticated users to book resource/research equipment",
            "Added changes to the tools database structure and improved it's security",
          ],
          tech: [
            "PHP",
            "Javascript",
            "Jquery",
            "Html",
            "MySql",
            "PostgreSql",
            "CSS",
            "Git",
            "Virtualbox",
            "Ubuntu",
            "Rest",
          ],
        },
      ],
    },
    {
      name: "PT-SI",
      projects: [
        {
          name: "Document manager with Alfresco",
          team_size: 3,
          period: ["2010-05-02", "2010-11-02"],
          roles: ["Backend", "Frontend"],
          goals: [
            "Alfresco application analysis, feature planning, implementation and testing",
          ],
          tech: [
            "Javascript",
            "Html",
            "CSS",
            "Java",
            "Spring",
            "JSF",
            "Hibernate",
            "ID software",
            "Subversion",
            "Rest",
          ],
        },
        {
          name: "Document manager with KnowledgeTree",
          team_size: 3,
          period: ["2010-03-15", "2010-05-02"],
          roles: ["Backend", "Frontend"],
          goals: [
            "KnowledgeTree application analysis, feature planning, implementation and testing",
          ],
          tech: ["PHP", "Javascript", "Html", "CSS"],
        },
      ],
    },
  ],
};

export default DATA;
